### ISSUE TITLE
error $ docker-compose run hello

### ISSUE THREAD

**Issue by pascalandy** [aherve/simple-dockerized-dev-env#2]
from the master branch.

$ docker-compose run test

```
hello is loaded !

  count
    ✓ should return 1

  1 passing (8ms)

simple-dockerized-dev-env|master ⇒ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                         NAMES
bbb7ca56b48c        mongo:3                               "/entrypoint.sh mongo"   2 minutes ago       Up 2 minutes        27017/tcp                     simpledockerizeddevenv_db_1
17b3acde3cce        codekitchen/dinghy-http-proxy:2.0.3   "forego start -r"        32 minutes ago      Up 32 minutes       0.0.0.0:80->80/tcp, 443/tcp   dinghy_http_proxy
```

then, $ docker-compose run hello

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/app/src/hello.js:2:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

```

**Comment by pascalandy** [comment]
Also

$ docker-compose run hello npm list

```
test@1.0.0 /app
+-- UNMET DEPENDENCY babel@^6.5.2
+-- UNMET DEPENDENCY express@^4.13.4
+-- UNMET DEPENDENCY mocha@^2.4.5
`-- UNMET DEPENDENCY should@^8.2.2

npm ERR! missing: babel@^6.5.2, required by test@1.0.0
npm ERR! missing: express@^4.13.4, required by test@1.0.0
npm ERR! missing: mocha@^2.4.5, required by test@1.0.0
npm ERR! missing: should@^8.2.2, required by test@1.0.0
```

**Comment by straley** [comment]
It's because the `hello` service is losing the `node_modules` folder.  It needs to be added to the `docker-compose.yml` file like:

```
hello:
  links:
    - "db:db"
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  command: node ./src/hello.js
  environment:
    - NODE_ENV=development

autotest:
  links:
    - "db:db"
  build: .
  volumes:
    - ./src:/app/src
    - /app/node_modules
  command: mocha ./src/hello.spec.js --watch
  environment:
    - NODE_ENV=test

test:
  links:
    - "db:db"
  build: .
  volumes:
    - ./src:/app/src
    - /app/node_modules
  command: mocha ./src/hello.spec.js
  environment:
    - NODE_ENV=test

db:
  image: mongo:3
```
